// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasources: {
    db: {
      provider: "postgresql",
      url: process.env["DATABASE_URL"],
    },
  },
  // Backwards-compatible single datasource URL used by some CLI commands
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
